easy_admin:
    site_name: "Admin d'Absinthe"
    disabled_actions: ['show']
    design:
      menu:
              - { label: 'Accueil Publique', url: '/', icon: 'home'}
              - label: 'Cours'
                children:
                    - {entity: 'Course', icon: 'pencil', default: true}
                    - {entity: 'Category', icon: 'inbox'}
                    - {entity: 'LabelCourse', icon: 'tags'}
              - label: 'Documents'
                children:
                    - {entity: 'Documents', icon: 'file'}
                    - {entity: 'LabelDocument', icon: 'tags'}
              - {entity: 'Users', icon: 'users'}
    user:
        name_property_path: 'email'
    list: 
        title: 'Liste des %%entity_label%%'
    entities:
      Course:
          class: App\Entity\Course
          label: 'Cours'
          list: 
                fields: 
                    - {property: 'name', label: 'Nom'}
                    - {property: 'createdAt',label: 'Ajouté le'}
                    - {property: 'courseCategory', label: 'Catégorie'}
                    - labels
                actions:
                    - {name: 'new', label: 'Créer un Cours'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-sm btn-primary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-sm btn-danger'}
          form:
              fields:
                  - {property: 'name', label: 'Nom'}
                  - {property: 'description',label: 'Description'}
                  - {property: 'duration',label: 'Durée (mois)'}
                  - {property: 'courseCategory', label: 'Catégorie'}
                  - {property: 'labels', label: 'Labels'}

      Category:
          class: App\Entity\CourseCategory
          label: 'Catégories'
          disabled_actions: ['delete']
          list: 
                title: 'Liste des %%entity_label%%'
                disabled_actions: ['delete']
                actions:
                    - {name: '-search'}
                    - {name: 'new', label: 'Créer une Catégorie'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-sm btn-primary'}
          edit:
                title: 'Modifier la catégorie %%entity_id%%'     
          form:
              fields:
                  - {property: 'semester',label: 'Semestre'}
                  - {property: 'promotion', label: 'Promotion'}

      LabelCourse:
          class: App\Entity\LabelCourse
          label: 'Labels'
          list: 
                actions:
                    - {name: 'new', label: 'Créer un Label'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-sm btn-primary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-sm btn-danger'}
          form:
            fields: 
                  - {property: 'name', label: 'Nom'}
      Users:
            class: App\Entity\User
            label: 'Utilisateurs'
            disabled_actions: ['new', 'edit']
            list:
                help: 'Vous pouvez ici supprimer des utilisateurs '
                fields: 
                    - email
                    - pseudo
                    - { property: 'created_at', label: 'Compte crée le', format: 'j/n/Y' }
                actions:
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-sm btn-danger'}
      Documents:
                class: App\Entity\CourseDocument
                label: 'Documents'
                disabled_actions: ['new', 'edit']
                list:
                    help: 'Vous pouvez ici supprimer des documents inadaptés'
                    fields: 
                        - name
                        - { property: 'author', label: 'Auteur' }
                        - { property: 'course', label: 'Cours' }
                        - { property: 'updatedAt', label: 'Ajouté le' }
                    actions:
                        - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-sm btn-danger'}
      LabelDocument:
          class: App\Entity\LabelDocument
          label: 'Labels'
          list: 
                actions:
                    - {name: 'new', label: 'Créer un Label'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-sm btn-primary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-sm btn-danger'}
          form:
            fields: 
                  - {property: 'name', label: 'Nom'}
