vich_uploader:
    db_driver: orm

    mappings:
       course_document:
           uri_prefix: /course/document
           upload_destination: '%kernel.project_dir%/public/course/document'
        #    namer: Vich\UploaderBundle\Naming\UniqidNamer
